### PR TITLE
log4cpp is not in ballister's sdk, and appears not to be used by even…

### PR DESCRIPTION
**Pull request by namccart**
…tstream

.... I'm not 100% sure you're not using log4cpp.  It's in Tom's sdk, but not ballister's... so until/unless we go static, it's a total PITA.  Should get rid of if we can.

### CODE REVIEW

**Comment by osh** [comment]
hrmmm .. there is talk about making log libs a dep for gnuradio I think 
@balister why is this not in your sdk? :

**Comment by osh** [comment]
@balister is adding it to the image now -- 
do we use log4cpp somewhere in the code? I would think just removing the check for it would break something unless we are actually not using it ...

**Comment by balister** [comment]
As a note, there is PACKAGECONFIG for logging that picks up log4cpp. It
i snot enabled by default. I note Corgan is talking about making it
required, so maybe I should drop the PACKAGECONFIG.

Philip

**Comment by osh** [comment]
so we can delete this PR now ?

**Comment by balister** [comment]
Yes. It will show up in newer builds. If you have issues with an older
build let me know and I can force it into updates

**Comment by osh** [comment]
closing for now

**Comment by namccart** [comment]
I still think we should leave these lines commented out until Balister's
image supports... there's just no reason to require it AFAIK, and losing
the cmake hasn't held me back at all.

Do you need me to open another PR?

Cheers,
Nick M.

**Pull request merged**
